In [75]:
import pandas as pd
from pathlib import Path

# Загрузка данных
data = pd.read_csv(Path.cwd().parent / "data/dataset_maxi_metrics.csv", index_col=0)

# Группировка и статистика
result = (
    data.groupby('level')["idiomatic_density_judge"]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result

   level    mean     std     min     max  count
0      0  0.0071  0.0181  0.0000  0.0735     21
1      1  0.0887  0.0724  0.0000  0.2990     42
2      2  0.1601  0.0758  0.0712  0.4000     21

In [77]:
result = (
    data[["bertscore_score", "bleurt_score", "comet_score", "meteor_score", "wmd_score"]]
    .agg(['mean', 'std'])
    .round(4)
    .reset_index()
)

result

  index  bertscore_score  bleurt_score  comet_score  meteor_score  wmd_score
0  mean           0.7378        0.2956       0.8555        0.2704     0.6950
1   std           0.0379        0.0663       0.0433        0.0676     0.0209

In [51]:
result = (
    data[["grammar", "fluency", "naturalness", "idiomacy", "idiom_diversity"]]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result

   index  grammar  fluency  naturalness  idiomacy  idiom_diversity
0   mean   4.9762   4.9643       4.9643    1.3452           3.5476
1    std   0.2182   0.2428       0.1867    0.7990           1.9101
2    min   3.0000   3.0000       4.0000    0.0000           0.0000
3    max   5.0000   5.0000       5.0000    2.0000           5.0000
4  count  84.0000  84.0000      84.0000   84.0000          84.0000

In [61]:
import pandas as pd
from pathlib import Path

# Загрузка данных
data1 = pd.read_csv(Path.cwd().parent / "data/all_generated_metrics.csv", index_col=0)

# Группировка и статистика
result = (
    data1.groupby(['model', 'size', 'level'])["idiomatic_density"]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result

      model size  level    mean     std  min     max  count
0   mistral   7b      0  0.1186  0.1285  0.0  0.4751     84
1   mistral   7b      1  0.1205  0.1250  0.0  0.4795     84
2   mistral   7b      2  0.1397  0.1159  0.0  0.5773     84
3   qwen2.5  14b      0  0.1053  0.1174  0.0  0.4762     84
4   qwen2.5  14b      1  0.1361  0.1246  0.0  0.5000     84
5   qwen2.5  14b      2  0.1865  0.1017  0.0  0.5685     84
6   qwen2.5   3b      0  0.0988  0.1195  0.0  0.6534     84
7   qwen2.5   3b      1  0.0977  0.1079  0.0  0.4144     84
8   qwen2.5   3b      2  0.1149  0.1353  0.0  0.4966     84
9   qwen2.5   7b      0  0.1167  0.1358  0.0  0.6593     84
10  qwen2.5   7b      1  0.1241  0.1101  0.0  0.5041     84
11  qwen2.5   7b      2  0.1366  0.1341  0.0  0.5657     84

In [62]:
result = (
    data1.groupby(['model', 'size'])[["grammar", "fluency", "naturalness", "idiomacy", "idiom_diversity"]]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result

     model size grammar                         fluency               ...  \
                   mean     std  min  max count    mean     std  min  ...
0  mistral   7b  4.7854  0.6169  1.0  5.0   247  4.6964  0.6991  2.0  ...
1  qwen2.5  14b  4.9919  0.0900  4.0  5.0   246  4.9715  0.2100  3.0  ...
2  qwen2.5   3b  4.8153  0.6334  1.0  5.0   249  4.7912  0.6062  2.0  ...
3  qwen2.5   7b  4.9076  0.3856  3.0  5.0   249  4.8594  0.4839  3.0  ...

  idiomacy                         idiom_diversity
      mean     std  min  max count            mean     std  min  max count
0   1.3644  0.7247  0.0  2.0   247          3.4453  1.7332  0.0  5.0   247
1   1.4919  0.7213  0.0  2.0   246          3.8455  1.6710  0.0  5.0   246
2   1.1245  0.7858  0.0  2.0   249          2.8594  1.9345  0.0  5.0   249
3   1.3213  0.7521  0.0  2.0   249          3.3735  1.7851  0.0  5.0   249

[4 rows x 27 columns]

In [63]:
data1.columns

Index(['text', 'ratio', 'level', 'model', 'size', 'grammar', 'fluency',
       'naturalness', 'idiomacy', 'idiom_diversity', 'idiomatic_expressions',
       'len_generated', 'len_idioms', 'idiomatic_density', 'literal_version',
       'original_text', 'bertscore_score', 'bleurt_score', 'comet_score',
       'meteor_score', 'wmd_score'],
      dtype='str')

In [78]:
result = (
    data1.groupby(['model', 'size'])[["bertscore_score", "bleurt_score", "comet_score",  "meteor_score", "wmd_score"]]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result

     model size bertscore_score                               bleurt_score  \
                           mean     std     min     max count         mean
0  mistral   7b          0.8370  0.0869  0.5894  0.9739   252       0.4018
1  qwen2.5  14b          0.7757  0.0642  0.6158  0.9178   252       0.3246
2  qwen2.5   3b          0.8141  0.0934  0.5730  0.9981   252       0.4443
3  qwen2.5   7b          0.8157  0.0910  0.5923  0.9804   252       0.4185

                   ... meteor_score                               wmd_score  \
      std     min  ...         mean     std     min     max count      mean
0  0.1148  0.1855  ...       0.6372  0.2380  0.0727  0.9634   252    0.8199
1  0.0919  0.1788  ...       0.4238  0.1606  0.0543  0.8860   252    0.7528
2  0.1392  0.0570  ...       0.5072  0.2675  0.0479  0.9939   252    0.7863
3  0.1400  0.1900  ...       0.5389  0.2671  0.0688  0.9796   252    0.7962


      std     min     max count
0  0.0838  0.6112  0.9821   252
1  0.0548  0.6283  0.9239   252
2  0.0974  0.5398  0.9974   252
3  0.0962  0.6163  0.9851   252

[4 rows x 27 columns]

In [7]:
def count_text_words(text):

    tokens = str(text).split()

    words_count = sum(1 for token in tokens if any(ch.isalpha() for ch in token))
    
    return words_count

data["len_generated"] = data['text'].apply(count_text_words)
data["len_idioms"] = data['idiomatic_expressions'].apply(count_text_words)
data["idiomatic_density"] = data["len_idioms"] / data["len_generated"]

data.head()

data.to_csv(Path.cwd().parent / "data/all_generated_judge.csv")