In [3]:
import pandas as pd
from pathlib import Path

# Загрузка данных
data = pd.read_csv(Path.cwd().parent / "data/dataset_maxi_metrics.csv", index_col=0)

# Группировка и статистика
result = (
    data.groupby(['text_domen'])["idiomatic_density_judge"]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result

       text_domen    mean     std     min     max  count
0       новостной  0.0222  0.0325  0.0000  0.1276     42
1  художественный  0.1502  0.0690  0.0508  0.4000     42

In [4]:
data.columns

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'author', 'source',
       'link', 'year_of_creation', 'text_domen', 'original_text',
       'idiomatic_expressions', 'literal_version', 'len_original',
       'len_idioms', 'idiomatic_density', 'len_literal', 'grammar', 'fluency',
       'naturalness', 'idiomacy', 'idiom_diversity',
       'idiomatic_expressions_judge', 'level', 'len_idioms_judge',
       'idiomatic_density_judge', 'bertscore_score', 'bleurt_score',
       'comet_score', 'meteor_score', 'wmd_score', 'abstractness_score',
       'sentiment', 'perplexity', 'coh_diff', 'word_freq_mean',
       'word_freq_coverage'],
      dtype='str')

In [5]:
result = (
    data[["bertscore_score", "bleurt_score", "comet_score", "meteor_score", "wmd_score"]]
    .agg(['mean'])
    .round(4)
    .reset_index()
)

result

  index  bertscore_score  bleurt_score  comet_score  meteor_score  wmd_score
0  mean           0.7378        0.2956       0.8555        0.2704      0.695

In [6]:
result = (
    data.groupby('level')[['abstractness_score', 'word_freq_mean', 'perplexity', 'coh_diff']]
    .agg(['mean'])
    .round(4)
    .reset_index()
)

result

  level abstractness_score word_freq_mean perplexity coh_diff
                      mean           mean       mean     mean
0     0             2.7923         4.1871     6.5658  -0.0045
1     1             2.6185         4.0678    10.8805  -0.0032
2     2             2.5319         3.8586    15.7276  -0.0028

In [7]:
result = data['sentiment'].value_counts()/84
result

sentiment
negative    0.607143
neutral     0.238095
positive    0.154762
Name: count, dtype: float64

In [8]:
result = (
    data.groupby('level')[["grammar", "fluency", "naturalness", "idiomacy", "idiom_diversity", "idiomatic_density_judge"]]
    .agg(['mean'])
    .round(4)
    .reset_index()
)

result

,level,grammar,fluency,naturalness,idiomacy,idiom_diversity,idiomatic_density_judge
,,mean,mean,mean,mean,mean,mean
0,0,5.0000,5.0000,4.9524,0.381,1.0952,0.0071
1,1,4.9524,4.9286,4.9524,1.500,4.0476,0.0887
2,2,5.0000,5.0000,5.0000,2.000,5.0000,0.1601

In [9]:
import pandas as pd
from pathlib import Path

# Загрузка данных
data1 = pd.read_csv(Path.cwd().parent / "data/all_generated_metrics.csv", index_col=0)

# Группировка и статистика
result = (
    data1.groupby(['model', 'size', 'level'])["idiomatic_density"]
    .agg(['mean', 'std', 'min', 'max', 'count'])
    .round(4)
    .reset_index()
)

result


data1['text_domen'] = data1['index_orig'].map(data.set_index('Unnamed: 0')['text_domen'])

In [11]:
result = (
    data1.groupby(['model', 'size', 'level'])[["grammar", "fluency", "naturalness", "idiomacy", "idiom_diversity"]]
    .agg(['median'])
    .round(4)
    .reset_index()
)

result

      model size level grammar fluency naturalness idiomacy idiom_diversity
                        median  median      median   median          median
0   mistral   7b     0     5.0     5.0         5.0      1.0             4.0
1   mistral   7b     1     5.0     5.0         5.0      1.0             4.0
2   mistral   7b     2     5.0     5.0         5.0      2.0             4.0
3   qwen2.5  14b     0     5.0     5.0         5.0      1.0             4.0
4   qwen2.5  14b     1     5.0     5.0         5.0      2.0             4.0
5   qwen2.5  14b     2     5.0     5.0         5.0      2.0             5.0
6   qwen2.5   3b     0     5.0     5.0         5.0      1.0             3.0
7   qwen2.5   3b     1     5.0     5.0         5.0      1.0             3.0
8   qwen2.5   3b     2     5.0     5.0         5.0      1.0             3.0
9   qwen2.5   7b     0     5.0     5.0         5.0      1.0             4.0
10  qwen2.5   7b     1     5.0     5.0         5.0      2.0             4.0
11  qwen2.5   7b     2     5.0     5.0         5.0      2.0             4.0

In [9]:
result = (
    data1.groupby(['model', 'size', 'level'])[["grammar", "fluency", "naturalness", "idiomacy", "idiom_diversity", "idiomatic_density"]]
    .agg(['mean'])
    .round(4)
    .reset_index()
)

result

,model,size,level,grammar,fluency,naturalness,idiomacy,idiom_diversity,idiomatic_density
,,,,mean,mean,mean,mean,mean,mean
0,mistral,7b,0,4.7831,4.7229,4.6988,1.2651,3.2289,0.1186
1,mistral,7b,1,4.7805,4.6341,4.5488,1.3415,3.3293,0.1205
2,mistral,7b,2,4.7927,4.7317,4.6951,1.4878,3.7805,0.1397
3,qwen2.5,14b,0,5.0000,4.9878,4.9756,1.1707,3.1707,0.1053
4,qwen2.5,14b,1,4.9878,4.9634,4.9634,1.4390,3.7317,0.1361
5,qwen2.5,14b,2,4.9878,4.9634,4.9512,1.8659,4.6341,0.1865
6,qwen2.5,3b,0,4.8313,4.8072,4.7590,1.0964,2.8434,0.0988
7,qwen2.5,3b,1,4.8690,4.7976,4.7738,1.1071,2.8333,0.0977
8,qwen2.5,3b,2,4.7439,4.7683,4.7317,1.1707,2.9024,0.1149
9,qwen2.5,7b,0,4.9634,4.9390,4.8659,1.2439,3.2805,0.1167
10,qwen2.5,7b,1,4.9759,4.9639,4.9398,1.3494,3.5181,0.1241
11,qwen2.5,7b,2,4.7857,4.6786,4.6071,1.3690,3.3214,0.1366

In [87]:
data1.columns

Index(['Unnamed: 0', 'index_orig', 'text', 'ratio', 'level', 'model', 'size',
       'grammar', 'fluency', 'naturalness', 'idiomacy', 'idiom_diversity',
       'idiomatic_expressions', 'len_generated', 'len_idioms',
       'idiomatic_density', 'literal_version', 'original_text',
       'bertscore_score', 'bleurt_score', 'comet_score', 'meteor_score',
       'wmd_score', 'abstractness_score', 'word_freq_mean',
       'word_freq_coverage', 'sentiment', 'perplexity', 'coh_diff'],
      dtype='str')

In [11]:
result = (
    data1.groupby(['model', 'size'])[["bertscore_score", "bleurt_score", "comet_score",  "meteor_score", "wmd_score"]]
    .agg(['mean'])
    .round(4)
    .reset_index()
)

result

,model,size,bertscore_score,bleurt_score,comet_score,meteor_score,wmd_score
,,,mean,mean,mean,mean,mean
0,mistral,7b,0.8370,0.4018,0.8547,0.6372,0.8199
1,qwen2.5,14b,0.7757,0.3246,0.8525,0.4238,0.7528
2,qwen2.5,3b,0.8141,0.4443,0.8424,0.5072,0.7863
3,qwen2.5,7b,0.8157,0.4185,0.8494,0.5389,0.7962

In [127]:
result = data1.groupby(['model', 'size'])['sentiment'].value_counts()/84/3

result

model    size  sentiment
mistral  7b    negative     0.468254
               neutral      0.365079
               positive     0.166667
qwen2.5  14b   negative     0.507937
               neutral      0.301587
               positive     0.190476
         3b    neutral      0.424603
               negative     0.420635
               positive     0.154762
         7b    negative     0.448413
               neutral      0.380952
               positive     0.170635
Name: count, dtype: float64

In [19]:
result = (
    data1.groupby(['model', 'size', 'level'])[['abstractness_score', 'word_freq_mean', 'perplexity', 'coh_diff']]
    .agg(['mean'])
    .round(4)
    .reset_index()
)

result

      model size level abstractness_score word_freq_mean perplexity coh_diff
                                     mean           mean       mean     mean
0   mistral   7b     0             2.8457         4.1771     8.8001  -0.0036
1   mistral   7b     1             2.8392         4.1972     8.6707  -0.0042
2   mistral   7b     2             2.8426         4.1907     8.8952  -0.0036
3   qwen2.5  14b     0             2.8352         4.1637     7.9191  -0.0036
4   qwen2.5  14b     1             2.8421         4.1549     8.5078  -0.0038
5   qwen2.5  14b     2             2.8219         4.0908     9.5914  -0.0042
6   qwen2.5   3b     0             2.8000         4.1700     9.2672  -0.0036
7   qwen2.5   3b     1             2.8002         4.1728     9.0146  -0.0046
8   qwen2.5   3b     2             2.8324         4.1701     8.9617  -0.0040
9   qwen2.5   7b     0             2.8305         4.1341     8.6338  -0.0042
10  qwen2.5   7b     1             2.8136         4.1315     9.1170  -0.0039
11  qwen2.5   7b     2             2.8727         4.1514     9.2323  -0.0031

In [7]:
def count_text_words(text):

    tokens = str(text).split()

    words_count = sum(1 for token in tokens if any(ch.isalpha() for ch in token))
    
    return words_count

data["len_generated"] = data['text'].apply(count_text_words)
data["len_idioms"] = data['idiomatic_expressions'].apply(count_text_words)
data["idiomatic_density"] = data["len_idioms"] / data["len_generated"]

data.head()

data.to_csv(Path.cwd().parent / "data/all_generated_judge.csv")